services:
  moodle:
    image: moodlehq/moodle-php-apache:8.3
    container_name: moodle
    restart: always
    ports:
      - "8001:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - MOODLE_DATABASE_TYPE=mysqli
      - MOODLE_DATABASE_HOST=base-prod-restaurada.c3o8ui2u4fhv.us-east-1.rds.amazonaws.com
      - MOODLE_DATABASE_NAME=markupdb_moodle
      - MOODLE_DATABASE_USER=markUpHost
      - MOODLE_DATABASE_PASSWORD=AwsDataBase.MarkUp2024

  composer:
    image: composer:2
    working_dir: /var/www/html

    volumes:
      - ./:/var/www/html
      - /home/ubuntu/PhpProjects/moodledata:/var/www/moodledata
      - ./php/moodle.ini:/usr/local/etc/php/conf.d/99-moodle.ini:ro
      - ./apache/moodle-router.conf:/etc/apache2/conf-enabled/moodle-router.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
